### ISSUE TITLE
USER STORY: View Paginated list of recipes

### ISSUE THREAD

**Issue by dasic002** [dasic002/virtual_recipe_book#1]
As a **site user** I can **view a paginated list of recipes** so that **I can select which to read further**

### Acceptance Criteria
- Given there are plenty of recipes in the database, recipes are viewed as a list
- When a user opens the homepage a list of recipes is visible.
- The recipes listed will display a title, an image, rating and prep time

### Tasks:
- [x] Create the view
- [x] Create the template
- [x] Create the URL
- [x] Add pagination
- [x] Style page
