### ISSUE TITLE
USER STORY: Modify or delete comment on a recipe

### ISSUE THREAD

**Issue by dasic002** [dasic002/virtual_recipe_book#15]
As a **site user** I can **modify or delete my comment on a recipe** so that ** so that I can be involved in the conversation.**

### Acceptance criteria
- The logged in user can modify their comment
- The logged in user can delete their comment

### Tasks:
- [x] Add POST and GET methods to recipe view
- [x] Add modify and delete buttons to template 
- [x] Add modal to confirm deletion of comment
- [x] Reset comment approval status on modification
