### ISSUE TITLE
USER STORY: Add a rating to a recipe

### ISSUE THREAD

**Issue by dasic002** [dasic002/virtual_recipe_book#16]
As a **site user** I can **rate recipes I have tried** so that **others get a subjective review from the community.**

### Acceptance criteria
- The logged in user can only submit a single review on a recipe
- The user may change their review
- The logged in user may opt to send a written review with the rating, but the comment is not displayed until the recipe owner has approved to publish

### Tasks:
- [ ] Create Rating model
- [ ] Add rating to recipe view
- [ ] Add rating to recipe templates to display running average and reviews section
