### ISSUE TITLE
USER STORY: Add a recipe to weekly meal planner

### ISSUE THREAD

**Issue by dasic002** [dasic002/virtual_recipe_book#19]
As a **site user** I can **build a weekly meal planner** so that **I can plan the recipes I wish to cook for the week.**

### Acceptance criteria
- Allows user to add the recipe and number of services to the planner
- Allows user to add the same recipe in other slots of the planner

### Tasks:
- [ ] Add planner model
- [ ] Add planner view
- [ ] Add planner template
