### ISSUE TITLE
USER STORY: Open Recipe

### ISSUE THREAD

**Issue by dasic002** [dasic002/virtual_recipe_book#2]
As a **site user** I can **click on a recipe** so that **I can read further**

### Acceptance criteria
- Recipe steps and ingredients are listed clearly
- Ratings and reviews are available to read
- Click on the rating jumps to rating section
- Ratings and reviews are available to read
- Adding a rating, as an optional comment field (subject to approval)
- "Save"/"Saved" button toggles to add/remove the recipe on the viewing user's collection

### Tasks:
- [x] Display recipe in template
- [x] Display rating average
- [x] Display save button
- [x] Display ratings/reviews breakdown
