### ISSUE TITLE
USER STORY: Add a meal planner to grocery list

### ISSUE THREAD

**Issue by dasic002** [dasic002/virtual_recipe_book#20]
As a **site user** I can **convert my meal planner into a grocery list** so that **I purchase only the ingredients I need.**

### Acceptance criteria
- 

### Tasks:
- [ ] Add grocery list model
- [ ] Add grocery list view
- [ ] Add grocery list template
- [ ]
